name: Auto-deployment of Documentation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0 # Ensures full history for deployment

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install Poetry Manually
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user poetry
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc

    - name: Verify Poetry Installation
      run: |
        export PATH=$HOME/.local/bin:$PATH
        which poetry || echo "Poetry not found in PATH"
        poetry --version || echo "Poetry command failed"

    - name: Configure Poetry to Use Python 3.11
      run: |
        poetry env use python3.11

    - name: Install dependencies
      run: |
        export PATH=$HOME/.local/bin:$PATH
        poetry install --with docs

    - name: Build documentation
      run: |
        mkdir -p src/oak_agent        
        export PATH=$HOME/.local/bin:$PATH
        echo ${{ secrets.GH_TOKEN }} >> src/oak_agent/token.txt
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry run sphinx-apidoc -o . ../src/aurelian/ --ext-autodoc -f
        poetry run sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/

    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        force: true
        folder: gh-pages
        token: ${{ secrets.GH_TOKEN }}
