name: oak-agent QC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.11" ]  # Test both 3.9 and 3.11

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          version: 1.7.1  # Explicit latest version

      - name: Ensure Poetry is available
        run: |
          echo "POETRY_HOME=$HOME/.local" >> $GITHUB_ENV
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          source $GITHUB_ENV
          poetry --version  # Debugging step

      - name: Force Poetry to Use Correct Python Version
        run: poetry env use python${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check common spelling errors
        run: poetry run tox -e codespell

      - name: Check code quality with flake8
        run: poetry run tox -e lint

      - name: Test with pytest and generate coverage file
        run: poetry run tox -e py
